nba_pipeline:
  outputs:
    dev:
      dataset: nba_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: service_key_file_path
      location: US
      method: service-account
      priority: interactive
      project: your_project_id
      threads: 2
      type: bigquery
  target: dev