nba_pipeline:
  outputs:
    dev:
      dataset: nba_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/gbemike/Documents/nba_pipeline/gcp_key.json
      location: US
      method: service-account
      priority: interactive
      project: dezoomcamp-411023
      threads: 2
      type: bigquery
  target: dev