version: 2

sources:
  - name: nba_data
    tables:
      - name: player_names
        meta:
          dagster:
            asset_key: ["player_names"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: player_bio
        meta:
          dagster:
            asset_key: ["player_bio"]
      - name: player_roles
        meta:
          dagster:
            asset_key: ["player_roles"]
      - name: player_stats
        meta:
          dagster:
            asset_key: ["player_stats"]